name: red2green
description: Community-driven mobile platform for urban cleanliness

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.10
  cloud_functions: ^4.5.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  
  # State Management
  provider: ^6.1.1
  
  # UI & Media
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^18.0.0
  intl: ^0.19.0
  
  # Utilities
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Assets will be added when images/icons are provided
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Fonts will be added when font files are provided
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500